
( echo :load App.hs
  echo ">>>>>>>>>>>>>START"
  echo "Theory: del1 x (del1 y zs) = del1 y (del1 x zs)"
  echo "Subgoals generated by Isabelle:"
  echo "  1. (BASE) del1 x (del1 y []) = del1 y (del1 x [])"
  echo "  in Haskell: del1 0 (del1 []) = del1 1 (del0 []) =="
  echo (del1 0 $ del1 1 [0,1,2,3]^^^) == (del1 1 $ del1 0 [0,1,2,3]^^^)
  echo "  2. (INDUCTIVE STEP) !!a list. del1 x (del1 y list) = del1 y (del1 x list) ==> del1 x (del1 y (a # list)) = del1 y (del1 x (a # list))"
  echo "  So first part (HYPOTHESIS) in Haskell: del1 0 (del1 1 [0,1,2]) == del1 1 (del1 0 [0,1,2]) =="
  echo (del1 0 $ del1 1 [0,1,2]^^^) == (del1 1 $ del1 0 [0,1,2]^^^)
  echo "  and the second part (STEP) in Haskell: del1 0 $ del1 1 (0 : [0,1,2]) == del1 1 $ del1 0 (0 : [0,1,2]) =="
  echo (del1 0 $ del1 1 $ 0 : [0,1,2]^^^) == (del1 1 $ del1 0 $ 0 : [0,1,2]^^^)
  echo "<<<<<<<<<<<<<END"
) | ghci
